version: '3.7'
services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
    #ports:
    #  - 8123:8123
    networks:
      proxy:
      home-assistant:
    depends_on:
      - homeassistant-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hass.entrypoints=http"
      - "traefik.http.routers.hass.rule=Host(`hass.domain.io.vn`)"
      - "traefik.http.middlewares.hass-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.haos.middlewares=hass-https-redirect"
      - "traefik.http.routers.haos-secure.entrypoints=https"
      - "traefik.http.routers.hass-secure.rule=Host(`hass.domain.io.vn`)"
      - "traefik.http.routers.hass-secure.tls=true"
      - "traefik.http.routers.hass-secure.tls.certresolver=cloudflare" # change this to your cert resolver
      - "traefik.http.routers.hass-secure.service=hass"
      - "traefik.http.services.hass.loadbalancer.server.port=8123"
      - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true


  homeassistant-db:
    image: docker.io/postgres:16.3
    container_name: homeassistant-db
    restart: unless-stopped
    # Change that password, of course!
    environment:
      - POSTGRES_USER=homeassistant_user
      - POSTGRES_PASSWORD=xF2odDFSjd3DFsl0ZgfQsjnd55yH
      - POSTGRES_DB=homeassistant-db
      # ensure the database gets created correctly
      # https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - ./schemas:/var/lib/postgresql/data
    networks:
      home-assistant:
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
  home-assistant:
