services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=base64:+EDGbq8Du6J9OxPDrqTj4GwW7i/DY4OvWFLTKsZbbuY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=speedy
      - DB_PASSWORD=password
      - SPEEDTEST_SCHEDULE=5 * * * *
      - SPEEDTEST_SERVERS=54812
      - PRUNE_RESULTS_OLDER_THAN=
      - CHART_DATETIME_FORMAT=
      - DATETIME_FORMAT=
      - APP_TIMEZONE=
    volumes:
      - ./data:/config
      - ./to-custom-ssl-keys:/config/keys
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mariadb:10
    restart: always
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=speedy
      - MARIADB_PASSWORD=password
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:
