services:
  speedtest-tracker:
    container_name: speedtest-tracker
    # ports:
    #  - 8080:80
    # - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=base64:uztryN3qc4bjShtib+zp99xOVD9TPxLE7Bc3q4/kSyk=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=speedy
      - DB_PASSWORD=password
      - SPEEDTEST_SCHEDULE=5 * * * *
      - SPEEDTEST_SERVERS=54812
      - PRUNE_RESULTS_OLDER_THAN=
      - CHART_DATETIME_FORMAT=
      - DATETIME_FORMAT=
      - APP_TIMEZONE=
    volumes:
      - ./data:/config
      - ./to-custom-ssl-keys:/config/keys
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tubearchivist.entrypoints=http"
      - "traefik.http.routers.tubearchivist.rule=Host(`speedtest.tkp.io.vn`)"
      - "traefik.http.middlewares.tubearchivist-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tubearchivist.middlewares=tubearchivist-https-redirect"
      - "traefik.http.routers.tubearchivist-secure.entrypoints=https"
      - "traefik.http.routers.tubearchivist-secure.rule=Host(`speedtest.tkp.io.vn`)"
      - "traefik.http.routers.tubearchivist-secure.tls=true"
      - "traefik.http.routers.tubearchivist-secure.service=speedtest-tracker"
      - "traefik.http.services.tubearchivist.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true     
  db:
    image: mariadb:10
    restart: always
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=speedy
      - MARIADB_PASSWORD=password
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:
networks:
  proxy:
    external: true
