version: '3.3'
services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: unless-stopped
    volumes:
      - ./data:/opt/alist/data
      - /mnt/repository:/mnt
   # ports:
   #   - '5244:5244'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.alist.entrypoints=http"
      - "traefik.http.routers.alist.rule=Host(`alist.tkp.io.vn`)"
      - "traefik.http.middlewares.alist-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.alist.middlewares=alist-https-redirect"
      - "traefik.http.routers.alist-secure.entrypoints=https"
      - "traefik.http.routers.alist-secure.rule=Host(`alist.tkp.io.vn`)"
      - "traefik.http.routers.alist-secure.tls=true"
      - "traefik.http.routers.alist-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.alist-secure.service=alist"
      - "traefik.http.services.alist.loadbalancer.server.port=5244"
    security_opt:
      - no-new-privileges:true
networks:
  proxy:
    external: true
